# Site settings
title: Yancey's Personal Website
email: yancey0623@163.com
description: Yancey's blog
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: Yancey1989
permalink: /blog/:year/:month/:day/:title
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/Yancey1989/yancey1989.github.io/tree/master
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/Yancey1989/yancey1989.github.io/tree/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
duoshuo_shortname: yancey0623
duoshuo_url: "http://yancey0623.duoshuo.com"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#disqus_shortname: lixizhi
#disqus_url: "http://yancey.info"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false

theme: jekyll-theme-cayman